# Generated by Django 5.2 on 2025-05-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('nombreproyecto', models.CharField(db_column='nombreProyecto', max_length=30)),
                ('fechacreacion', models.DateField(db_column='fechaCreacion')),
                ('enlace', models.CharField(blank=True, null=True)),
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
