# Generated by Django 5.2 on 2025-05-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
    ]
