# Generated by Django 5.2 on 2025-05-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_proyecto_options'),
        ('tasks', '0005_remove_rol_administrador_remove_rol_colaborador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechacreacion',
            field=models.DateField(auto_now_add=True, db_column='fechacreacion'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombreproyecto',
            field=models.CharField(db_column='nombreproyecto', max_length=30),
        ),
    ]
