# Generated by Django 5.2 on 2025-05-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_proyecto_id_usuario_alter_proyecto_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fechacreacion'),
        ),
    ]
