# Generated by Django 5.2 on 2025-05-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_alter_proyecto_fechacreacion'),
        ('tasks', '0006_alter_rol_nombre_alter_usuario_rol_idrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', default=0, on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
            preserve_default=False,
        ),
    ]
