# Generated by Django 5.2 on 2025-06-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_alter_proyecto_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='id_proyecto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=django.db.models.deletion.CASCADE),
        ),
    ]
