# Generated by Django 5.2 on 2025-06-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_alter_proyecto_id_proyecto'),
        ('tasks', '0009_usuario_enlaceperfil'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='proyecto',
        #     name='enlace',
        # ),
        # migrations.CreateModel(
        #     name='ColaboradorProyecto',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
        #         ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
        #         ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
        #     ],
        #     options={
        #         'db_table': 'colaborador_proyecto',
        #         'unique_together': {('usuario', 'proyecto')},
        #     },
        # ),
    ]
