# Generated by Django 5.2 on 2025-04-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('colaborador', models.CharField(blank=True, max_length=45, null=True)),
                ('administrador', models.CharField(blank=True, max_length=45, null=True)),
                ('idrol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('estado', models.TextField()),
                ('correoelectronico', models.CharField(db_column='correoElectronico', max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
                ('suscripcion', models.TextField()),
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('terminoservicio', models.BooleanField(db_column='terminoServicio')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
    ]
