

services:
    backend:
      build: ./backend
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app
      working_dir: /app
      networks:
        - app-network
      env_file:
        - ./backend/backend/.env
      environment:
        - PYTHONIOENCODING=utf8

    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
        args:
          VITE_API_BASE: http://localhost:8000  # o la URL que necesites
      ports:
        - "80:80"  # Nginx escucha en el puerto 80
      depends_on:
        - backend
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
