# Generated by Django 5.2 on 2025-05-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rol_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
