# Generated by Django 5.2 on 2025-05-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_rol_options_alter_usuario_options'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='rol',
        #     name='administrador',
        # ),
        # migrations.RemoveField(
        #     model_name='rol',
        #     name='colaborador',
        # ),
        # migrations.AddField(
        #     model_name='rol',
        #     name='nombre',
        #     field=models.CharField(max_length=45, null=True),
        # ),
        # migrations.AddField(
        #     model_name='usuario',
        #     name='rol_idrol',
        #     field=models.ForeignKey(blank=True, db_column='rol_idRol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.rol'),
        # ),
        # migrations.AddField(
        #     model_name='usuario',
        #     name='token',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='rol',
        #     name='idrol',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
    ]
