# Generated by Django 5.2 on 2025-05-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_rol_administrador_remove_rol_colaborador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_idrol',
            field=models.ForeignKey(blank=True, db_column='rol_idRol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='idrol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
