# Generated by Django 5.2 on 2025-05-29 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_rol_administrador_remove_rol_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(default='generico', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_idrol',
            field=models.ForeignKey(blank=True, db_column='rol_idRol', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.rol'),
        ),
    ]
