# Generated by Django 5.2 on 2025-05-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_rol_nombre_alter_usuario_rol_idrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uuid_supabase',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
