# Generated by Django 5.2 on 2025-06-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_usuario_uuid_supabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='idrol',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=django.db.models.deletion.CASCADE),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idusuario',
            field=models.AutoField(db_column='idUsuario', primary_key=True, serialize=False, verbose_name=django.db.models.deletion.CASCADE),
        ),
    ]
