# Generated by Django 5.2 on 2025-06-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_rol_idrol_alter_usuario_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='enlacePerfil',
            field=models.URLField(blank=True, null=True),
        ),
    ]
