# Generated by Django 5.1.7 on 2025-09-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_usuario_enlaceperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_Tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTarea', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateField(blank=True, null=True)),
                ('fechaLimite', models.TimeField(blank=True, null=True)),
                ('fechaActual', models.DateTimeField(blank=True, null=True)),
                ('filtro', models.CharField(default='por completar', max_length=50)),
                ('tipoTarea', models.CharField(blank=True, max_length=50, null=True)),
                ('id_proyecto', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
    ]
