# Generated by Django 5.2 on 2025-09-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='idrol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idusuario',
            field=models.AutoField(db_column='idUsuario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_idrol',
            field=models.ForeignKey(blank=True, db_column='rol_idrol', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.rol'),
        ),
        migrations.AlterModelTable(
            name='rol',
            table='Rol',
        ),
    ]
