# Generated by Django 5.2 on 2025-09-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_rol_idrol_alter_usuario_idusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
