# Generated by Django 5.2 on 2025-06-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('idagendamiento', models.AutoField(db_column='idAgendamiento', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Agendamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('marca', models.CharField(max_length=30)),
                ('fotoequipo', models.CharField(blank=True, db_column='fotoEquipo', max_length=150, null=True)),
                ('numeroserie', models.CharField(db_column='numeroSerie', max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipoagendamiento',
            fields=[
                ('fechaingreso', models.DateField(db_column='fechaIngreso')),
                ('fechasalida', models.DateField(blank=True, db_column='fechaSalida', null=True)),
                ('comentarioentrada', models.CharField(blank=True, db_column='comentarioEntrada', null=True)),
                ('comentariosalida', models.CharField(blank=True, db_column='comentarioSalida', null=True)),
                ('estado', models.TextField(db_column='Estado')),
                ('agendamiento_equipo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'EquipoAgendamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.CharField(max_length=45)),
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('proyecto', models.ForeignKey(blank=True, db_column='proyecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'Cliente',
                'managed': True,
            },
        ),
    ]
